#!/bin/bash
(
OWRT=./
  ./buildroot-2020.02/output/host/bin/qemu-system-aarch64 -M virt -m 1024M\
  -cpu cortex-a53 -nographic -smp 1 -kernel ${OWRT}/openwrt-19.07.2-armvirt-64-Image\
  -append "rootwait root=/dev/vda console=ttyAMA0" -netdev user,id=eth0,hostfwd=tcp::8888-:8810,hostfwd=tcp::2222-:22\
  -device virtio-net-device,netdev=eth0\
  -drive file=${OWRT}/root.ext4,if=none,format=raw,id=hd0\
  -device virtio-blk-device,drive=hd0\
  -soundhw hda -audiodev id=pa,driver=pa

#  -device usb-ehci \
#  -device piix4-usb-uhci \
#  -usb -device usb-hub \
#  -device usb-host,vendorid=0x0d8c,productid=0x000c
)
